# Generated by Django 5.2 on 2025-05-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
