# Generated by Django 5.2 on 2025-05-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_content_title_remove_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('short', 'Short answer'), ('long', 'Long answer'), ('radio', 'Multiple choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('range', 'Linear scale'), ('date', 'Date')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.section'),
        ),
    ]
