# Generated by Django 5.2 on 2025-05-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_question_answer_type_alter_question_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.section'),
        ),
    ]
