# Generated by Django 5.2 on 2025-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_content_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('short', 'Short answer'), ('long', 'Long answer'), ('radio', 'Multiple choice'), ('checkbox', 'Checkboxes'), ('range', 'Linear scale'), ('date', 'Date')], max_length=10),
        ),
    ]
