# Generated by Django 5.2 on 2025-06-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_answer_submitted_at_remove_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.submition'),
        ),
    ]
