# Generated by Django 5.2 on 2025-06-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_alter_answer_submition'),
    ]

    operations = [
        migrations.AddField(
            model_name='submition',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
    ]
